"""
Generates a downloadable PDF prediction report using fpdf2.
Pure-python, no system dependencies -> safe for Render's free tier.
"""

from fpdf import FPDF
from datetime import datetime

NAVY = (13, 19, 48)
BLUE = (59, 130, 246)
CYAN = (6, 182, 212)
GREEN = (34, 197, 94)
RED = (239, 68, 68)
GRAY = (100, 116, 139)


class ReportPDF(FPDF):
    def header(self):
        self.set_fill_color(*NAVY)
        self.rect(0, 0, 210, 28, "F")
        self.set_xy(10, 8)
        self.set_font("Helvetica", "B", 16)
        self.set_text_color(255, 255, 255)
        self.cell(0, 8, "CreditSense", ln=1)
        self.set_x(10)
        self.set_font("Helvetica", "", 9)
        self.set_text_color(180, 200, 230)
        self.cell(0, 6, "AI-Powered Credit Card Approval Report", ln=1)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(*GRAY)
        self.cell(0, 10, f"Generated by CreditSense | Page {self.page_no()}", align="C")


def build_report(result, prediction_id=None):
    pdf = ReportPDF()
    pdf.add_page()
    pdf.set_y(34)

    # Decision banner
    color = GREEN if result["approved"] else RED
    pdf.set_fill_color(*color)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 14, f"  DECISION: {result['prediction_label'].upper()}", fill=True, ln=1)
    pdf.ln(4)

    pdf.set_text_color(20, 20, 20)

    def kv_row(label, value):
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(*GRAY)
        pdf.cell(60, 9, label)
        pdf.set_font("Helvetica", "", 11)
        pdf.set_text_color(20, 20, 20)
        pdf.cell(0, 9, str(value), ln=1)

    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(*BLUE)
    pdf.cell(0, 10, "Prediction Summary", ln=1)
    pdf.set_draw_color(*BLUE)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(3)

    if prediction_id:
        kv_row("Prediction ID:", f"#{prediction_id:06d}")
    kv_row("Applicant:", result["applicant_name"])
    kv_row("Approval Probability:", f"{result['probability']}%")
    kv_row("Confidence Score:", f"{result['confidence']}%")
    kv_row("Risk Category:", result["risk_label"])
    if result["approved"]:
        kv_row("Recommended Credit Limit:", f"${result['credit_limit']:,.0f}")
        kv_row("Estimated Interest Rate (APR):", f"{result['interest_rate']}%")
    kv_row("Model Used:", result["model_used"])
    kv_row("Prediction Time:", f"{result['prediction_time_ms']} ms")
    kv_row("Generated On:", datetime.now().strftime("%d %b %Y, %I:%M %p"))

    pdf.ln(6)
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(*BLUE)
    pdf.cell(0, 10, "Applicant Details", ln=1)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(3)

    inputs = result["inputs"]
    detail_pairs = [
        ("Gender", inputs["gender"]),
        ("Age", f"{int(inputs['age'])} yrs"),
        ("Annual Income", f"${inputs['income']:,.0f}"),
        ("Income Type", inputs["income_type"]),
        ("Education", inputs["education"]),
        ("Family Status", inputs["family_status"]),
        ("Housing Type", inputs["housing_type"]),
        ("Occupation", inputs["occupation"]),
        ("Children", inputs["children"]),
        ("Family Members", inputs["family_members"]),
        ("Years Employed", inputs["years_employed"]),
        ("Owns Car", inputs["own_car"]),
        ("Owns Property", inputs["own_house"]),
    ]
    for label, value in detail_pairs:
        kv_row(label + ":", value)

    pdf.ln(6)
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(*BLUE)
    pdf.cell(0, 10, "AI Explanation", ln=1)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(3)
    pdf.set_font("Helvetica", "", 10.5)
    pdf.set_text_color(40, 40, 40)
    pdf.multi_cell(0, 6, result["explanation"])

    pdf.ln(4)
    pdf.set_font("Helvetica", "I", 8.5)
    pdf.set_text_color(*GRAY)
    pdf.multi_cell(
        0, 5,
        "Disclaimer: This is a demonstration report generated as part of the "
        "SmartBridge Summer Internship project. It does not constitute a real "
        "credit decision or financial advice."
    )

    return bytes(pdf.output())
